- src/components/CommunityCard/styles.module.css
- src/pages/index.module.css
- src/pages/index.tsx
Removing sections and updating CSS for docs landing page until content and branding is ready.
Closes #1
> Style change: Update CSS and remove sections temporarily

- src/pages/index.tsx
Remove section line added in [this PR](https://github.com/immutable/imx-docs/pull/5) and used a whitespace gap instead.
Closes #1
> Style update: Remove section line and introduce whitespace gap instead

- src/components/ArticleStack/index.tsx
- src/components/ArticleStack/styles.module.css
- src/components/CommunityCard/index.tsx
- src/components/CommunityCard/styles.module.css
- src/components/Footer/index.tsx
- src/components/GlobalHeader/index.tsx
- src/pages/index.module.css
- src/pages/index.tsx
Fix some styling issues highlighted by the team in [this Slack thread](https://imtbl.slack.com/archives/C0337K0U73K/p1654065762695409), including:
* Ensuring external links open in a new tab
* Formatting of components on different page sizes
* Ensure text is contained in buttons when resized
Closes #1
> Style update: Fix styling and link issues with homepage

- .github/PULL_REQUEST_TEMPLATE.md
- docs/troubleshooting/generate-imx-signature.md
This PR:
* Adds a page in the docs with information on how to get the `IMX-Signature` in the headers for the following endpoints:
* **collections**
* [createCollection](https://docs.x.immutable.com/reference#/operations/createCollection)
* [updateCollection](https://docs.x.immutable.com/reference#/operations/updateCollection)
* **metadata**
* [addMetadataSchemaToCollection](https://docs.x.immutable.com/reference#/operations/addMetadataSchemaToCollection)
* [updateMetadataSchemaByName](https://docs.x.immutable.com/reference#/operations/updateMetadataSchemaByName)
* **projects**
* [getProjects](https://docs.x.immutable.com/reference#/operations/getProjects)
* [getProject](https://docs.x.immutable.com/reference#/operations/getProject)
* …
> [DXP-861] Add docs for how to get the IMX-Signature

- src/css/custom.css
Accidentally made links red in [previous commit](https://github.com/immutable/imx-docs/pull/15/commits/1090975360cff2f0ad29ea34ced71a192b95530c).
**Before:**
**After:**
Jira:
> Style: Fix red links accidentally added in previous commit

- docs/overview/contributing.md
> [NT] Update contributing.md

- docs/overview/introduction-smart-contracts.md
There are a couple of words missing (if I understood the context correctly).
Proposing a couple of typo fixes to the last two paragraphs. 
Jira: no ticket as it's just a typo fix.
> [NT] docs: Update introduction-smart-contracts.md

- docs/guides/link-sdk/link-cryptotofiat.md
Update a sentence for offramp
Jira: https://immutable.atlassian.net/browse/WT-494
> docs: WT-494: update offramp sentence

- docs/guides/getting-started-guide.md
https://faucet.ropsten.be/ is end-of-life’d, so let’s remove this as it’s redundant.
Jira: https://immutable.atlassian.net/browse/DX-953
> fix: Remove end-of-life faucet

- docs/guides/asset-management/asset-metadata.mdx
- docs/guides/asset-management/asset-minting.md
- docs/guides/minting-on-immutable-x.md
- docs/guides/onboarding/collection-registration.mdx
- docs/guides/onboarding/index.md
- docs/guides/onboarding/metadata-schema-registration.mdx
- docs/guides/onboarding/project-registration.md
- docs/resources/contact.mdx
- docs/troubleshooting/developer-faq.md
Updating our contact support URLs
> update contact support URLs

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template doc for this repo to include instructions for internal Immutable devs when submitting to imx-docs and when adding or updating guides/SDK docs.
Jira: N/A
> docs: update PR template with section for internal devs

- docusaurus.config.js
- src/components/Footer/index.tsx
- src/components/Footer/styles.module.css
- src/css/custom.css
This PR:
- Adds a divider between the mobile Navbar items and the social content
- Collapses the footer flexbox as a column for mobile view
- Fixes mobile nav styling
Mobile Nav:
Footer:
Introduced by: https://github.com/immutable/imx-docs/pull/14
Jira: https://immutable.atlassian.net/browse/DX-957
> fix: responsiveness for footer and mobile nav

- src/css/custom.css
In https://github.com/immutable/imx-docs/pull/42, a few attributes were missing including punctuation, operators, booleans, and numbers. This PR adds these.
Jira: https://immutable.atlassian.net/browse/DX-889
> fix(api): dark mode style punctuation, operators, booleans & numbers

- docs/sdks/Core SDK Kotlin JVM.md
- docs/sdks/Core SDK Typescript.md
Adds a notice about the Core SDK interface being unstable
Jira:
> chore: adds a notice about the Core SDK interface being unstable

- docs/guides/fees/index.md
Remove "coming soon" message from royalty fees table.
Also convert the HTML table to a markdown table.
> docs: Remove coming soon message from royalty fees table.

- .github/workflows/release.yml
Relevant to https://github.com/immutable/imx-docs/pull/55, [we can see here](https://github.com/immutable/imx-docs/runs/7510212820?check_suite_focus=true#step:7:435) that our husky hooks are causing our semantic-release publish action to hang.
This PR adds the `HUSKY=0` env variable to our semantic-release call to release, [which will bypass husky hooks](https://typicode.github.io/husky/#/?id=bypass-hooks).
Jira: https://immutable.atlassian.net/browse/DX-996
> fix(hooks): ensure release doesnt hang due to husky hooks

- docusaurus.config.js
- src/css/custom.css
- src/theme/DocSidebar/index.tsx
- src/theme/DocSidebar/styles.module.css
Fix the brief code flash when initially navigating to the SDK page.
Jira:
> fix: SDK docs code flash

- postcss.config.js
- sdks-core-sdk-ts_versioned_docs/version-0.6.0/overview.md
- src/theme/DocSidebar/index.tsx
Disable the SDK switcher and Tailwind to fix the styling while styling on the switcher gets resolved.
Jira: https://immutable.atlassian.net/browse/DX-1025
> fix: docs styling fix

- docs/main/guides/link-sdk/link-setup.md
Add a minimal version that we support for GME walelt
Jira:
> docs: wt-551: add gamestop requirements

- README.md
- sidebars/sidebars-core-sdk-swift.js
- sidebars/sidebars-core-sdk-ts.js
- src/theme/versions/versions.json
Update README with more info about document instance versioning, which will also automagically update the SDK version switcher.
Also removed unused `versions.json` config file that is not actually used by the version switrcher.
Jira: https://immutable.atlassian.net/browse/DX-1063
> [DX-1063] add docs for a newly published SDK version

- src/components/SurvicateWidget/index.tsx
Reverts immutable/imx-docs#77 as there was a bug caused by https://github.com/immutable/imx-docs/compare/main...revert-77-DX-1059/route-team-surveys?expand=1#diff-da75d209f5cea9a2a0d03001f0ec4afd6f2b5ba12659a8f3d5a3ce641ad72b54L139
> Revert "feat: Tag rating survey with article team ownership"

- src/components/SurvicateWidget/index.tsx
Re-implements https://github.com/immutable/imx-docs/pull/77, although with correct reference to the Survicate window object.
Jira: https://immutable.atlassian.net/browse/DX-1081
> fix(survicate): configure survicate traits when sva will always exist

- .github/PULL_REQUEST_TEMPLATE.md
Add instructions on how to add ownership of pages to PR template
Jira: https://immutable.atlassian.net/browse/DX-1058
> [DX-1058] Add instructions on how to add ownership of pages to PR template

- src/components/SdkSwitcher/index.tsx
Fixes this issue: [Slack message](https://imtbl.slack.com/archives/C030DMV2S73/p1660710965210679)
Jira:
> fix: fix switcher to ignore version in url

- docs/main/guides/wallet-sdk-ui-guide.md
The guide with the recommended UI/UX expected when partners use the Wallet SDK.
The guidelines we will recommend to partners who adopt the Wallet-SDK-web in conjunction with the Core-SDK.
> Wallet SDK UI/UX Guide

- docs/main/guides/wallet-sdk-ui-guide.md
Adding missing elements in the user interactions list, making images a bit larger and hyperlinks.
Adding missing elements in the user interactions list, making images a bit larger and hyperlinks.
> Fix user interactions list and image sizes

- docs/sdk-docs/wallet-sdk-web/overview.md
Add wallet UI guide link into the documentation list.
Add wallet UI guide link into the documentation list.
> Add wallet UI guide link into documentation list

- docs/sdk-docs/core-sdk-ts/quickstart.md
- docs/sdk-docs/wallet-sdk-web/reference.md
Synchronizing docs with their **current** related repository READMEs.
Jira:
https://immutable.atlassian.net/browse/WT-804
https://immutable.atlassian.net/browse/WT-807
> docs: WT-804/WT-807 - Core SDK and Wallet SDK doc sync-ups with their README versions

- docs/main/troubleshooting/api-changelog.md
- docusaurus.config.js
- src/css/custom.css
This PR:
* Adds `API changelog` as a dropdown for the API navbar header
* Adds an API changelog Markdown page as a new page in docs
* Adds `Changelog` as a sidebar attribute for Typescript Core SDK docs
Jira: https://immutable.atlassian.net/browse/DX-1062
> [DX-1062] Feat: Add API changelog

- docs/sdk-docs/wallet-sdk-web/overview.md
As our repository is still not open source, users are facing an error page when clicking the link. We need to update it to the npm package page.
Jira:
> Update Immutable overview github repo link

- docusaurus.config.js
This PR adds a link to the API reference in the API navbar dropdown because previously it only contained the changelog, and it wasn't clear that you could access the reference via the top level link.
Before:
After:
Jira: N/A
> feat: Add link to API reference in API navbar dropdown

- docs/main/guides/asset-management/asset-minting.md
Somehow merge conflict syntax / code block thing got added to the code snippet in the minting example. This PR resolves the merge conflict in the code snippet.
Jira: https://immutable.atlassian.net/browse/DX-1240
> [DX-1240] docs: fix code snippet

- docs/sdk-docs/core-sdk-ts/installation.md
- sdks-core-sdk-ts_versioned_docs/version-1.0.0-beta.2/installation.md
Fix TS Core SDK 1.0.0 beta.2 installation guide.
Jira:
>  fix(ts core sdk installation guide): update 1.0.0 beta.2 installation guide

- docs/main/guides/asset-management/asset-ownership.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/guides/asset-management/asset-ownership.mdx
updates get asset json payload
jira ticket: https://immutable.atlassian.net/browse/GMS-121
> GMS-121: updates get asset example to the current format

- docs/main/guides/onboarding/project-registration.md
The heading hierarchy for project limits has been updated to indicate that collection limits and mint limits are both associated with a project, and that project limits contain both mint and collection limits.
Jira: https://immutable.atlassian.net/browse/GMS-310
> fix: project limits heading hierarchy

- docs/sdk-docs/core-sdk-ts/changelog.md
- sdks-core-sdk-ts_versioned_docs/version-1.0.0-beta.3/changelog.md
- sdks-core-sdk-ts_versioned_sidebars/version-1.0.0-beta.3-sidebars.json
- sidebars/sidebars-core-sdk-ts.js
Added changelog to core sdk typescript sidebar
[DX-1307]
Jira:
[DX-1307]: https://immutable.atlassian.net/browse/DX-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(core-sdk-ts): add changelog

- docs/sdk-docs/core-sdk-ts/metadata-refresh.md
- sdks-core-sdk-ts_versioned_docs/version-1.0.0-beta.3/metadata-refresh.md
- sdks-core-sdk-ts_versioned_sidebars/version-1.0.0-beta.3-sidebars.json
- sidebars/sidebars-core-sdk-ts.js
We learned that it’s not clear how Game Devs can use the Core SDK "simply", without doing a full Core SDK migration and a full Core SDK install.
This PR adds examples about using the `core typescript sdk` to request and track metadata refreshes for assets so it's easier for new developers to get started with our SDKs.
> docs: Add examples for metadata refreshes

- docs/main/tutorials/zero-to-hero-nft-minting.md
Adds additional environment variables that need to be updated to launch in mainnet
> docs: update mainnet launch steps in zero-to-hero-nft-minting.md

- docs/main/tutorials/zero-to-hero-nft-minting.md
Fixes markdown for PR: https://github.com/immutable/imx-docs/pull/153
> docs: fix markdown

- docs/main/guides/link-sdk/link-errors.md
- docs/main/guides/link-sdk/link-iframe-support.md
- i18n/ko/docusaurus-plugin-content-docs/current/guides/link-sdk/link-errors.md
- i18n/ko/docusaurus-plugin-content-docs/current/guides/link-sdk/link-iframe-support.md
Jira: https://immutable.atlassian.net/browse/WT-886
> docs: Removing Link whitelist communications from docs.

- docs/main/guides/integrate-your-application/immutable-x-sdk.md
- docs/main/guides/integrate-your-application/marketplaces.md
- docs/main/guides/integrate-your-application/personal-inventory.md
This PR adds some clarifying improvements to the docs about various things.
Jira: https://immutable.atlassian.net/jira/software/c/projects/GMS/boards/289?modal=detail&selectedIssue=GMS-229
> [GMS-229] Small clarifying doc improvements

- docs/main/guides-new/deposit-withdrawals/index.mdx
Added code example for Asset deposits - TypeScript Core SDK. 
Jira:
> docs(guides-new): TypeScript CoreSDK guides updates

- docs/main/guides/link-sdk/link-iframe-support.md
- i18n/ko/docusaurus-plugin-content-docs/current/guides/link-sdk/link-iframe-support.md
Jira: https://immutable.atlassian.net/browse/BT-75
> docs: Adding infomation about mobile experience into the Link iFrame docs.

- src/pages/index.module.css
- src/pages/index.tsx
Describe your pull request here.
Jira: https://immutable.atlassian.net/browse/DX-1337
> [DX-1337] style: update landing page copy

- docs/main/overview/start-here.md
Describe your pull request here.
Jira:
> fix: fixes broken links in the start-here page

- docs/main/tutorials/zero-to-hero-nft-minting.md
Fixed Marketplace link in zero-to-hero-minting-tutorial to the correct sandbox marketplace. Made changes to the headings for step 6.
Jira:
> fixes: link not working, heading changes

- docs/main/guides/link-sdk/link-nft-checkout-primary.md
PT-161
Improved docs for Moonpay primary checkout
Jira: PT-151
> docs: improved documentation for moonpay checkout 

- docs/main/guides/link-sdk/link-errors.md
- i18n/ko/docusaurus-plugin-content-docs/current/guides/link-sdk/link-errors.md
As part of the efforts to improve the [IMX client methods that handle location checks](https://immutable.atlassian.net/browse/WT-876) it was needed to add some new errors on the following Link flows:
- Deposit
- Buy
- Sell
- Transfer
Jira: https://immutable.atlassian.net/browse/WT-876
> docs: Link - Error messages for API rejections

- sdks-core-sdk-golang_versioned_sidebars/version-0.2.1-sidebars.json
- sdks-core-sdk-kotlin_versioned_sidebars/version-0.6.0-sidebars.json
- sdks-core-sdk-swift_versioned_sidebars/version-0.4.0-sidebars.json
- sdks-core-sdk-ts_versioned_sidebars/version-1.0.0-beta.3-sidebars.json
- sidebars/sidebars-core-sdk-golang.js
- sidebars/sidebars-core-sdk-kotlin.js
- sidebars/sidebars-core-sdk-swift.js
- sidebars/sidebars-core-sdk-ts.js
This PR just adds Github links within the SDK docs to reference the SDK repo.
Jira:
> docs: add github outlink to sdk ref docs

- docs/sdk-docs/core-sdk-kotlin/overview.md
- sdks-core-sdk-kotlin_versioned_docs/version-1.0.0-beta.1/overview.md
Remove Kotlin/JVM unstable warning message to align with TS Core SDK.
> docs: remove Kotlin Core SDK unstable warning message

- docs/main/guides/link-sdk/offers/index.md
- docs/main/guides/link-sdk/offers/link-accept-offer.md
- docs/main/guides/link-sdk/offers/link-cancel-offer.md
- docs/main/guides/link-sdk/offers/link-make-offer.md
Signed-off-by: Frank Li <b439988l@gmail.com>
Describe your pull request here.
Jira:
> Update warning message for offers

- docs/main/key-concepts/deep-dive-metadata.md
Provide more fundamental information about metadata and a comparison of its storage options so that users have a better understanding of how to structure their L1 and L2 metadata.
Jira: https://immutable.atlassian.net/browse/DX-1401
> [DX-1401] docs: add more info to metadata article

- docs/main/guides/basic-guides/deposits-withdrawals/index.md
- docs/main/guides/js-sdk/minting-with-royalties.md
This PR updates the deposit and withdrawal guides with API instructions.
Jira: https://immutable.atlassian.net/browse/DX-1402
> [DX-1402] docs: add deposit withdrawal api guides

- docs/main/troubleshooting/developer-faq.md
Remove outdated instructions for metadata refresh and point to docs for self-serve
> docs: update metadata refresh instructions in developer-faq.md

- docs/main/guides/advanced-guides/asset-metadata-refreshes.md
We have increased the limits for metadata refresh from 5 to 10 per hour. This updates the documentation to reflect this change.
Describe your pull request here.
Jira:
> Update limit of metadata refresh requests

- docs/main/launch-collection/register-project/index.mdx
- docs/main/tutorials/zero-to-hero-nft-minting.md
Add instructions to sign up to the developer hub.
Jira: https://immutable.atlassian.net/browse/DX-1375
> docs: create project step

- docs/main/guides/basic-guides/create-trades/index.md
Fixes a minor typo pointed out by a Discord user.
> docs: Fix minor typo

- docs/main/guides/link-sdk/offers/link-accept-offer.md
- docs/main/guides/link-sdk/offers/link-make-offer.md
Signed-off-by: Frank Li <b439988l@gmail.com>
Add fees array as supported to offer functions
Jira:
> feat: Add fees array to create and accept offer

- docs/main/key-concepts/deep-dive-api-concepts.md
- package.json
Update api headers doc with message required for `x-imx-eth-signature` header
Jira: https://immutable.atlassian.net/browse/DX-1679
> [DX-1679] docs: update api headers doc with message required for `x-imx-eth-signature` header

- docs/main/guides/advanced-guides/asset-metadata-refreshes.md
we have now updated refresh limits from 10 to 20 per hour
> docs: update refresh limits
